grails-app/domain/rovshenamazon/ConfigParams.groovy
package rovshenamazon

class ConfigParams {
    String k
    String v
    static constraints = {
        v nullable: true, blank: true
    }
}

grails-app/domain/rovshenamazon/Profile.groovy
package rovshenamazon

class Profile {
    String name
    String ranking
    String image
    String path
    static hasMany = [profileReviews: ProfileReview]
    static constraints = {
        image nullable: true, blank: true
    }
}

grails-app/domain/rovshenamazon/ProfileReview.groovy
package rovshenamazon

class ProfileReview {
    static belongsTo = [review: Review, profile: Profile]
    static constraints = {
    }
}

grails-app/domain/rovshenamazon/Review.groovy
package rovshenamazon

class Review {
    String title
    String title1
    String name
    String nameLink
    int startCount //starCount1
    String date
    String title2
    String color
    String colorLink
    String verified
    String reviewContent
    String image1
    String image2
    String image3
    String image4
    String image5
    String image6
    String image7
    String image8
    String productImage
    String productTitle
    String productTitleLink
    String byWhom
    String byWhomLink
    String starCount
    String customerRatingsText
    int star5Perc
    int star4Perc
    int star3Perc
    int star2Perc
    int star1Perc
    String price
    String shippingInfo
    String path
    Integer helpfulVotes
    static constraints = {
        title nullable: true, blank: true
        title1 nullable: true, blank: true
        name nullable: true, blank: true
        startCount nullable: true, blank: true
        title2 nullable: true, blank: true
        color nullable: true, blank: true
        verified nullable: true, blank: true
        reviewContent nullable: true, blank: true
        image1 nullable: true, blank: true
        image2 nullable: true, blank: true
        image3 nullable: true, blank: true
        image4 nullable: true, blank: true
        image5 nullable: true, blank: true
        image6 nullable: true, blank: true
        image7 nullable: true, blank: true
        image8 nullable: true, blank: true
        productImage nullable: true, blank: true
        productTitle nullable: true, blank: true
        byWhom nullable: true, blank: true
        starCount nullable: true, blank: true
        customerRatingsText nullable: true, blank: true
        star5Perc nullable: true, blank: true
        star4Perc nullable: true, blank: true
        star3Perc nullable: true, blank: true
        star2Perc nullable: true, blank: true
        star1Perc nullable: true, blank: true
        price nullable: true, blank: true
        shippingInfo nullable: true, blank: true
    }
}

grails-app/controllers/rovshenamazon/AdministratorController.groovy
package rovshenamazon

class AdministratorController {
    def adminService

    def index() {
        def list = Review?.findAll([sort: 'id', order: 'desc', max: 1000])
        [list: list]
    }

    def add() {
        [review: Review?.get(params?.getLong('id'))]
    }

    def saveReview() {
        adminService.saveReview(params, request)
        redirect(action: 'index')
    }

    def delete() {
        adminService.delete(params)
        redirect(action: 'index')
    }

    def generalParams() {
        def configParams = ConfigParams?.findAll()
        [configParams: configParams]
    }

    def saveConfigParams() {
        adminService.saveConfigParams(params)
        redirect(action: 'generalParams')
    }

    def profileList() {
        def profiles = Profile?.findAll()
        [profiles: profiles]
    }

    def addProfile() {
        def profile = Profile?.get(params?.getLong('id'))
        [profile: profile]
    }

    def deleteProfile() {
        adminService.deleteProfile(params)
        redirect(action: 'profileList')
    }

    def saveProfile() {
        adminService.saveProfile(params, request)
        redirect(action: 'profileList')
    }
}

grails-app/controllers/rovshenamazon/HomeController.groovy
package rovshenamazon

class HomeController {
    def info() {
        def review = Review?.findByPath(params?.id)

        def starIconStarCount
        if (review.starCount.contains('.5')) {
            starIconStarCount = review.starCount.replace(".", "-")
        } else {
            starIconStarCount = Double.parseDouble(review.starCount).round().toString().replace(".", "-")
        }
        [review: review, starIconStarCount: starIconStarCount]
    }

    def profile() {
        def profile = Profile?.findByPath(params?.path)
        def helpfulVotes = profile?.profileReviews?.review?.helpfulVotes?.sum()
        [profile: profile, helpfulVotes: helpfulVotes]
    }
}

grails-app/controllers/rovshenamazon/ImageDisplayerController.groovy
package rovshenamazon

import grails.util.Holders

class ImageDisplayerController {
    def cookieService
    def sourcePath = Holders.config.source.path

    def index() {
        def photoPath = sourcePath
        def photoName = params?.photoName

        String specificFolder
        File photo

        try {
            if (photoName.isEmpty() || photoName == null || photoName.equals("null")) {
                specificFolder = sourcePath + "/default"
                photo = new File(specificFolder + ".png")
                response.setHeader("Content-disposition", "inline")
            } else {
                specificFolder = photoPath
                photo = new File(specificFolder + File.separator + photoName)
                response.setHeader("Content-disposition", "inline")
            }
            if (photo.exists()) {
                response.setContentType("image/jpeg")
                response.outputStream << (photo.bytes)
                response.outputStream.flush()
                response.setHeader("Content-disposition", "inline")
            } else {
                specificFolder = photoPath
                photo = new File(photoPath + File.separator + photoName)
                response.setHeader("Content-disposition", "inline")
            }
        } catch (Exception e) {
            e.stackTrace
        }
        return
    }
}

grails-app/views/administrator/add.gsp
<meta name="layout" content="mainAdmin"/>

<div class="col-md-8 col-md-offset-2">
    <g:uploadForm action="saveReview" id="${review?.id}">
        <div class="form-group">
            <label>Title:</label>
            <input class="form-control" name="title" type="text" value="${review?.title}"/>
        </div>

        <div class="form-group">
            <label>Title 1:</label>
            <input class="form-control" name="title1" type="text" value="${review?.title1 ?: 'Kundenrezension'}"/>
        </div>

        <div class="form-group">
            <label>Name:</label>
            <input class="form-control" name="name" type="text" value="${review?.name}"/>
        </div>

        <div class="form-group">
            <label>Name link:</label>
            <input class="form-control" name="nameLink" type="text" value="${review?.nameLink}"/>
        </div>

        <div class="form-group">
            <label>Star count 1:</label>
            <input class="form-control" name="startCount" type="number" value="${review?.startCount}"/>
        </div>

        <div class="form-group">
            <label>Date:</label>
            <input class="form-control" name="date" type="text" value="${review?.date}"/>
        </div>

        <div class="form-group">
            <label>Title2:</label>
            <input class="form-control" name="title2" type="text" value="${review?.title2}"/>
        </div>

        <div class="form-group">
            <label>Color:</label>
            <input class="form-control" name="color" type="text" value="${review?.color}"/>
        </div>

        <div class="form-group">
            <label>Color Link:</label>
            <input class="form-control" name="colorLink" type="text" value="${review?.colorLink}"/>
        </div>

        <div class="form-group">
            <label>Verified text:</label>
            <input class="form-control" name="verified" type="text"
                   value="${review?.verified ?: 'Verifizierter Kauf'}"/>
        </div>

        <div class="form-group">
            <label>Review content:</label>
            <textarea class="form-control" name="reviewContent">
                ${review?.reviewContent}
            </textarea>
        </div>

        <div class="form-group">
            <label>Product Title:</label>
            <input class="form-control" name="productTitle" type="text" value="${review?.productTitle}"/>
        </div>

        <div class="form-group">
            <label>Product Title link:</label>
            <input class="form-control" name="productTitleLink" type="text" value="${review?.productTitleLink}"/>
        </div>

        <div class="form-group">
            <label>By whom:</label>
            <input class="form-control" name="byWhom" type="text" value="${review?.byWhom}"/>
        </div>

        <div class="form-group">
            <label>By whom link:</label>
            <input class="form-control" name="byWhomLink" type="text" value="${review?.byWhomLink}"/>
        </div>

        <div class="form-group">
            <label>Star count:</label>
            <input class="form-control" name="starCount" type="text" value="${review?.starCount ?: '5'}"/>
        </div>

        <div class="form-group">
            <label>Customer Ratings Text:</label>
            <input class="form-control" name="customerRatingsText" type="text" value="${review?.customerRatingsText}"/>
        </div>

        <div class="form-group">
            <label>5 star percent:</label>
            <input class="form-control" name="star5Perc" type="number" value="${review?.star5Perc}"/>
        </div>

        <div class="form-group">
            <label>4 star percent:</label>
            <input class="form-control" name="star4Perc" type="number" value="${review?.star4Perc}"/>
        </div>

        <div class="form-group">
            <label>3 star percent:</label>
            <input class="form-control" name="star3Perc" type="number" value="${review?.star3Perc}"/>
        </div>

        <div class="form-group">
            <label>2 star percent:</label>
            <input class="form-control" name="star2Perc" type="number" value="${review?.star2Perc}"/>
        </div>

        <div class="form-group">
            <label>1 star percent:</label>
            <input class="form-control" name="star1Perc" type="number" value="${review?.star1Perc}"/>
        </div>

        <div class="form-group">
            <label>Price:</label>
            <input class="form-control" name="price" type="text" value="${review?.price ?: ' €'}"/>
        </div>

        <div class="form-group">
            <label>Shipping Info:</label>
            <input class="form-control" name="shippingInfo" type="text" value="${review?.shippingInfo}"/>
        </div>


        <div class="form-group">
            <label>Review Images:</label>
            <input multiple class="form-control" name="reviewImages" type="file"/>
        </div>

        <div class="form-group">
            <label>Product Image:</label>
            <input class="form-control" name="productImages" type="file"/>
        </div>

        <div class="form-group">
            <label>Helpful votes:</label>;
            <input class="form-control" name="helpfulVotes" required type="number"
                   value="${review?.helpfulVotes ?: 0}"/>
        </div>

        <div class="form-group">
            <label>Path:</label>
            <input class="form-control" name="path" value="${review?.path}"/>
        </div>

        <div class="form-group">
            <button class="btn btn-primary pull-right" type="submit">Save</button>
        </div>
    </g:uploadForm>
</div>

grails-app/views/administrator/addProfile.gsp
<meta name="layout" content="mainAdmin"/>

<div class="col-md-8 col-md-offset-2">
    <g:uploadForm action="saveProfile" id="${profile?.id}">
        <div class="form-group">
            <label>Full name:</label>
            <input class="form-control" name="name" type="text" value="${profile?.name}"/>
        </div>

        <div class="form-group">
            <label>Ranking:</label>
            <input class="form-control" name="ranking" type="text" value="${profile?.ranking}"/>
        </div>

        <div class="form-group">
            <label>Reviews:</label> <br/>
            <g:each in="${rovshenamazon.Review?.findAll([sort: 'id', order: 'desc', max: 1000])}" var="r">
                <div class="input-group">
                    <span class="input-group-addon">
                        <input <g:if test="${profile?.profileReviews?.find { it.review.id == r.id }}">checked</g:if>
                               type="checkbox"
                               name="review" value="${r.id}"/>
                    </span>

                    <p class="form-control">
                        <a href="${createLink(controller: 'home', action: 'info', id: r?.path)}">${r.title}</a>
                    </p>
                </div> <br/>
            </g:each>
        </div>
        <div class="form-group">
            <label>Path:</label>
            <input class="form-control" required name="path" value="${profile?.path}"/>
        </div>
        <div class="form-group">
            <label>Image:</label>
            <input class="form-control" name="image" type="file"/>
        </div>


        <div class="form-group">
            <button class="btn btn-primary pull-right" type="submit">Save</button>
        </div>
    </g:uploadForm>
</div>

grails-app/views/administrator/generalParams.gsp
<meta name="layout" content="mainAdmin"/>

<div class="col-md-8 col-md-offset-2">
    <g:form action="saveConfigParams">
        <div class="form-group">
            <label>Title:</label>
            <input class="form-control" name="title" type="text"
                   value="${configParams?.find { it.k.equals('title') }?.v}"/>
        </div>

        <div class="form-group">
            <label>Favicon:</label>
            <input class="form-control" name="favicon" type="text"
                   value="${configParams?.find { it.k.equals('favicon') }?.v}"/>
        </div>

        <div class="form-group">
            <label>Logo:</label>
            <input class="form-control" name="logo" type="text"
                   value="${configParams?.find { it.k.equals('logo') }?.v}"/>
        </div>

        <div class="form-group">
            <label>Show price line:</label>
            <input type="checkbox" name="showPrice"
                   value="1"
                   <g:if test="${configParams?.find { it.k.equals('showPrice') }?.v?.equals('1')}">checked</g:if>/>
        </div>
        <hr/>

        <g:each in="${1..20}" var="num">
            <div class="col-md-12">
                <div class="col-md-6">
                    <label>Navbar title:</label>
                    <input class="form-control" name="navTitle${num}" type="text"
                           value="${configParams?.find { it.k.equals('navTitle' + num) }?.v}"/>
                </div>

                <div class="col-md-6">
                    <label>Navbar path:</label>
                    <input class="form-control" name="navLink${num}" type="text"
                           value="${configParams?.find { it.k.equals('navLink' + num) }?.v}"/>
                </div>
            </div>

        </g:each>


        <div class="form-group" style="margin-top: 650px;margin-bottom: 700px">
            <button class="btn btn-primary pull-right" type="submit">Save</button>
        </div>
    </g:form>
</div>

grails-app/views/administrator/index.gsp
<meta name="layout" content="mainAdmin"/>

<table class="table table-bordered">
    <thead>
    <th>Review</th>
    <th>Edit</th>
    <th>Delete</th>
    </thead>
    <tbody>
    <g:each in="${list}" var="review">
        <tr>
            <td>
                <a href="${createLink(controller: 'home', action: 'info', id: review?.path)}">${review?.title}</a>
            </td>
            <td>
                <a href="${createLink(action: 'add', id: review?.id)}">
                    Edit
                </a>
            </td>
            <td>
                <a style="color:red" href="${createLink(action: 'delete', id: review?.id)}">
                    Delete
                </a>
            </td>
        </tr>
    </g:each>

    </tbody>
</table>

grails-app/views/administrator/profileList.gsp
<meta name="layout" content="mainAdmin"/>

<div class="col-md-8 col-md-offset-2">
    <table class="table table-bordered">
        <thead>
        <th>Image</th>
        <th>Full Name</th>
        <th>Ranking</th>
        <th>Edit</th>
        <th>Delete</th>
        </thead>
        <tbody>
        <g:each in="${profiles}" var="profile">
            <tr>
                <td>
                    <g:link controller="home" action="profile" params="[path: profile?.path]">
                        <img src="${createLink(controller: 'imageDisplayer', action: 'index', params: [photoName: profile.image])}"
                             style="width: 100px;height: 100px"/>
                    </g:link>
                </td>
                <td>${profile?.name}</td>
                <td>${profile?.ranking}</td>
                <td>
                    <g:link action="addProfile" id="${profile?.id}">
                        <img class="oper-icon" src="${resource(dir: 'icon', file: 'edit.svg')}"/>
                    </g:link>
                </td>
                <td>
                    <g:link action="deleteProfile" id="${profile?.id}">
                        <img class="oper-icon" src="${resource(dir: 'icon', file: 'delete.svg')}"/>
                    </g:link>
                </td>
            </tr>
        </g:each>
        </tbody>
    </table>

</div>

<g:link action="addProfile" class="add">
    <img src="${resource(dir: 'icon', file: 'add.svg')}"/>
</g:link>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="Grails"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
    <g:layoutHead/>
    <r:layoutResources/>
</head>

<body>
<style>
#nav-belt {
    background-color: #232f3e!important;
}
</style>

<div id="grailsLogo" role="banner"><a href="http://grails.org"><img
        src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
<g:layoutBody/>
<div class="footer" role="contentinfo"></div>

<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
<g:javascript library="application"/>
<r:layoutResources/>
</body>
</html>

grails-app/views/layouts/mainAdmin.gsp
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<link rel='stylesheet' href='${resource(dir: 'css', file: 'custom.css')}'/>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><g:link controller="administrator" action="index">List</g:link></li>
                <li><g:link controller="administrator" action="add">Add new</g:link></li>
                <li><g:link controller="administrator" action="profileList">Profiles</g:link></li>
                <li><g:link controller="administrator" action="generalParams">General params</g:link></li>
            </ul>

        </div>
    </div>
</nav>

<div class="container-fluid">

    <div class="row">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

        <div class="col-md-8 col-md-offset-2">
            <g:layoutBody/>
        </div>
    </div>
</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.min.js"></script>